// Copyright (c) 2026 Scott W. Corley
// SPDX-License-Identifier: Apache-2.0

package emit_llvm_test

import (
	"strings"
	"testing"

	"github.com/candor-core/candor/compiler/emit_llvm"
	"github.com/candor-core/candor/compiler/lexer"
	"github.com/candor-core/candor/compiler/parser"
	"github.com/candor-core/candor/compiler/typeck"
)

func compileLL(t *testing.T, src string) string {
	t.Helper()
	tokens, err := lexer.Tokenize("test.cnd", src)
	if err != nil {
		t.Fatalf("lex: %v", err)
	}
	file, err := parser.Parse("test.cnd", tokens)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	res, err := typeck.Check(file)
	if err != nil {
		t.Fatalf("typeck: %v", err)
	}
	out, err := emit_llvm.EmitLLVM(file, res, "")
	if err != nil {
		t.Fatalf("emit_llvm: %v", err)
	}
	return out
}

// compileLLErr runs the full pipeline and returns the emitter error (if any).
// Unlike compileLL it does not call t.Fatal on emit errors.
func compileLLErr(t *testing.T, src string) (string, error) {
	t.Helper()
	tokens, err := lexer.Tokenize("test.cnd", src)
	if err != nil {
		t.Fatalf("lex: %v", err)
	}
	file, err := parser.Parse("test.cnd", tokens)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	res, err := typeck.Check(file)
	if err != nil {
		t.Fatalf("typeck: %v", err)
	}
	return emit_llvm.EmitLLVM(file, res, "")
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("expected IR to contain %q\nGot:\n%s", needle, haystack)
	}
}

func TestEmitHeader(t *testing.T) {
	out := compileLL(t, `fn main() -> unit { return unit }`)
	assertContains(t, out, `; LLVM IR generated by Candor compiler`)
	assertContains(t, out, `target triple = "x86_64-unknown-linux-gnu"`)
}

func TestEmitHeaderCustomTarget(t *testing.T) {
	tokens, _ := lexer.Tokenize("t.cnd", `fn main() -> unit { return unit }`)
	file, _ := parser.Parse("t.cnd", tokens)
	res, _ := typeck.Check(file)
	out, err := emit_llvm.EmitLLVM(file, res, "aarch64-unknown-linux-gnu")
	if err != nil {
		t.Fatalf("emit_llvm: %v", err)
	}
	assertContains(t, out, `target triple = "aarch64-unknown-linux-gnu"`)
}

func TestEmitMainWrapper(t *testing.T) {
	out := compileLL(t, `fn main() -> unit { return unit }`)
	assertContains(t, out, `define void @_cnd_main()`)
	assertContains(t, out, `define i32 @main()`)
	assertContains(t, out, `call void @_cnd_main()`)
	assertContains(t, out, `ret i32 0`)
}

func TestEmitReturnInt(t *testing.T) {
	out := compileLL(t, `fn add(a: i64, b: i64) -> i64 { return a + b }`)
	assertContains(t, out, `define i64 @add`)
	assertContains(t, out, `add i64`)
	assertContains(t, out, `ret i64`)
}

func TestEmitLetBinding(t *testing.T) {
	out := compileLL(t, `fn foo() -> i64 { let x: i64 = 42 return x }`)
	assertContains(t, out, `alloca i64`)
	assertContains(t, out, `store i64 42`)
	assertContains(t, out, `load i64`)
	assertContains(t, out, `ret i64`)
}

func TestEmitIfElse(t *testing.T) {
	out := compileLL(t, `fn abs(x: i64) -> i64 {
		if x < 0 { return -x } else { return x }
	}`)
	assertContains(t, out, `icmp slt i64`)
	assertContains(t, out, `br i1`)
	assertContains(t, out, `then.`)
	assertContains(t, out, `else.`)
}

func TestEmitWhile(t *testing.T) {
	out := compileLL(t, `fn countdown(n: i64) -> unit {
		let mut i: i64 = n
		while i > 0 { i = i - 1 }
	}`)
	assertContains(t, out, `while.hdr`)
	assertContains(t, out, `while.body`)
	assertContains(t, out, `while.exit`)
	assertContains(t, out, `icmp sgt i64`)
}

func TestEmitLoop(t *testing.T) {
	out := compileLL(t, `fn forever() -> unit {
		loop { break }
	}`)
	assertContains(t, out, `loop.body`)
	assertContains(t, out, `loop.exit`)
	assertContains(t, out, `br label %loop.exit`)
}

func TestEmitStringLiteral(t *testing.T) {
	out := compileLL(t, `fn greet() -> str { return "hello" }`)
	assertContains(t, out, `@.str.0`)
	assertContains(t, out, `constant`)
	assertContains(t, out, `hello`)
}

func TestEmitStruct(t *testing.T) {
	out := compileLL(t, `
struct Point { x: i64, y: i64 }
fn make_point(x: i64, y: i64) -> Point {
	return Point { x: x, y: y }
}
fn get_x(p: Point) -> i64 { return p.x }
`)
	assertContains(t, out, `%Point = type { i64, i64 }`)
	assertContains(t, out, `insertvalue %Point`)
	assertContains(t, out, `extractvalue %Point`)
}

func TestEmitExternDecl(t *testing.T) {
	out := compileLL(t, `
extern fn puts(s: str) -> i32
fn main() -> unit {
	puts("hi")
}
`)
	assertContains(t, out, `declare i32 @puts(ptr)`)
}

func TestEmitBoolOps(t *testing.T) {
	out := compileLL(t, `fn check(a: bool, b: bool) -> bool { return a and b }`)
	assertContains(t, out, `and i1`)
}

func TestEmitCast(t *testing.T) {
	out := compileLL(t, `fn to_f64(x: i64) -> f64 { return x as f64 }`)
	assertContains(t, out, `sitofp i64`)
	assertContains(t, out, `to double`)
}

func TestEmitEnum(t *testing.T) {
	out := compileLL(t, `
enum Color { Red, Green, Blue }
fn make_red() -> Color { return Color::Red }
`)
	assertContains(t, out, `%Color = type { i32 }`)
	assertContains(t, out, `insertvalue %Color zeroinitializer, i32 0`)
}

func TestEmitArithmeticOps(t *testing.T) {
	out := compileLL(t, `
fn ops(a: i64, b: i64) -> i64 {
	let x: i64 = a * b
	let y: i64 = x / 2
	let z: i64 = y % 3
	return z
}`)
	assertContains(t, out, `mul i64`)
	assertContains(t, out, `sdiv i64`)
	assertContains(t, out, `srem i64`)
}

func TestEmitEnumPayloadMatch(t *testing.T) {
	out := compileLL(t, `
enum Opt { None, Some(i64) }
fn unwrap(o: Opt) -> i64 {
	match o {
		Opt::Some(x) => x,
		_ => 0,
	}
}
`)
	assertContains(t, out, `switch i32`)
	assertContains(t, out, `getelementptr %Opt`)
	assertContains(t, out, `load i64`)
}

func TestEmitTupleDestructure(t *testing.T) {
	out := compileLL(t, `fn swap(a: i64, b: i64) -> i64 {
	let (x, y) = (b, a)
	return x
}`)
	assertContains(t, out, `extractvalue`)
	assertContains(t, out, `alloca i64`)
}

func TestEmitAddressOf(t *testing.T) {
	out := compileLL(t, `
extern fn uses_ptr(p: ref<i64>) -> unit
fn foo(x: i64) -> unit {
	uses_ptr(&x)
}
`)
	assertContains(t, out, `call void @uses_ptr`)
}

func TestEmitForInVec(t *testing.T) {
	out := compileLL(t, `
extern fn make_vec() -> vec<i64>
fn sum() -> i64 {
	let v: vec<i64> = make_vec()
	let mut total: i64 = 0
	for x in v { total = total + x }
	return total
}
`)
	assertContains(t, out, `extractvalue %_cnd_vec`)
	assertContains(t, out, `for.hdr`)
	assertContains(t, out, `for.body`)
	assertContains(t, out, `for.incr`)
	assertContains(t, out, `for.exit`)
	assertContains(t, out, `icmp ult i64`)
}

func TestEmitIndexAssignVec(t *testing.T) {
	out := compileLL(t, `
fn zero_first(v: vec<i64>) -> unit {
	v[0] = 0
}
`)
	assertContains(t, out, `getelementptr %_cnd_vec`)
	assertContains(t, out, `store i64`)
}

func TestEmitVecIndexRead(t *testing.T) {
	out := compileLL(t, `
fn first(v: vec<i64>) -> i64 {
	return v[0]
}
`)
	assertContains(t, out, `extractvalue %_cnd_vec`)
	assertContains(t, out, `load i64`)
}

func TestEmitVecLiteral(t *testing.T) {
	out := compileLL(t, `fn make() -> vec<i64> { return [10, 20, 30] }`)
	assertContains(t, out, `call ptr @malloc`)
	assertContains(t, out, `getelementptr i64`)
	assertContains(t, out, `store i64 10`)
	assertContains(t, out, `store i64 20`)
	assertContains(t, out, `store i64 30`)
	assertContains(t, out, `insertvalue %_cnd_vec`)
}

func TestEmitVecLiteralForIn(t *testing.T) {
	out := compileLL(t, `fn sum() -> i64 {
	let v: vec<i64> = [1, 2, 3]
	let mut total: i64 = 0
	for x in v { total = total + x }
	return total
}`)
	assertContains(t, out, `call ptr @malloc`)
	assertContains(t, out, `for.hdr`)
	assertContains(t, out, `icmp ult i64`)
}

func TestNoMainWrapper_WithoutMain(t *testing.T) {
	out := compileLL(t, `fn add(a: i64, b: i64) -> i64 { return a + b }`)
	if strings.Contains(out, `define i32 @main()`) {
		t.Errorf("should not emit i32 @main when no Candor main exists")
	}
}

func TestEmitMapForIn(t *testing.T) {
	out := compileLL(t, `
extern fn use_kv(k: i64, v: bool) -> unit
fn scan(m: map<i64, bool>) -> unit {
	for k, v in m {
		use_kv(k, v)
	}
}`)
	assertContains(t, out, `%_cnd_map = type { ptr, i64, i64 }`)
	assertContains(t, out, `%_cnd_map_entry_i64_i1 = type { i64, i1, ptr }`)
	assertContains(t, out, `getelementptr %_cnd_map`)
	assertContains(t, out, `map.inner.hdr`)
	assertContains(t, out, `icmp ne ptr`)
}

func TestEmitLambdaBasic(t *testing.T) {
	out := compileLL(t, `
fn apply(x: i64) -> i64 {
	let f = fn(n: i64) -> i64 { return n + 1 }
	return 0
}`)
	assertContains(t, out, `@_cnd_lambda_1_impl`)
	assertContains(t, out, `{ ptr, ptr }`)
	assertContains(t, out, `call ptr @malloc`)
}

func TestEmitLambdaWithCapture(t *testing.T) {
	out := compileLL(t, `
fn make_adder(x: i64) -> i64 {
	let f = fn(n: i64) -> i64 { return n + x }
	return 0
}`)
	assertContains(t, out, `%_cnd_lambda_1_env = type { i64 }`)
	assertContains(t, out, `@_cnd_lambda_1_impl`)
	assertContains(t, out, `getelementptr %_cnd_lambda_1_env`)
}

func TestEmitLambdaCall(t *testing.T) {
	out := compileLL(t, `
fn run() -> i64 {
	let f = fn(n: i64) -> i64 { return n + 1 }
	return f(5)
}`)
	assertContains(t, out, `@_cnd_lambda_1_impl`)
	assertContains(t, out, `getelementptr { ptr, ptr }`)
	assertContains(t, out, `call i64`)
}

func TestEmitVecPush(t *testing.T) {
	out := compileLL(t, `
fn build() -> unit {
	let mut v: vec<i64> = vec_new()
	vec_push(v, 10)
	vec_push(v, 20)
	return unit
}`)
	// realloc must be declared for grow path
	assertContains(t, out, `declare ptr @realloc(ptr, i64)`)
	// grow branch: icmp eq len cap
	assertContains(t, out, `icmp eq i64`)
	// element store via GEP into data pointer
	assertContains(t, out, `getelementptr i64`)
	// len is incremented
	assertContains(t, out, `add i64`)
}

func TestEmitVecPop(t *testing.T) {
	out := compileLL(t, `
fn shrink() -> i64 {
	let mut v: vec<i64> = vec_new()
	vec_push(v, 42)
	return vec_pop(v)
}`)
	assertContains(t, out, `declare ptr @realloc(ptr, i64)`)
	// pop decrements len: sub i64 ... 1
	assertContains(t, out, `sub i64`)
	// returns element via GEP load
	assertContains(t, out, `getelementptr i64`)
	assertContains(t, out, `ret i64`)
}

func TestEmitRingPushBack(t *testing.T) {
	out := compileLL(t, `
fn fill() -> unit {
	let mut r: ring<i64> = ring_new(4)
	ring_push_back(r, 1)
	ring_push_back(r, 2)
	return unit
}`)
	assertContains(t, out, `%_cnd_ring = type { ptr, i64, i64, i64 }`)
	// grow path uses malloc for new buffer
	assertContains(t, out, `call ptr @malloc`)
	// tail index: (head+len)%cap uses unsigned remainder
	assertContains(t, out, `urem i64`)
}

func TestEmitBoxNew(t *testing.T) {
	out := compileLL(t, `
fn f() -> unit {
	let b: box<i64> = box_new(42)
	return unit
}`)
	// sizeof via GEP trick
	assertContains(t, out, `getelementptr i64, ptr null, i64 1`)
	assertContains(t, out, `ptrtoint ptr`)
	assertContains(t, out, `call ptr @malloc`)
	assertContains(t, out, `store i64 42`)
}

func TestEmitBoxDeref(t *testing.T) {
	out := compileLL(t, `
fn f() -> i64 {
	let b: box<i64> = box_new(7)
	return box_deref(b)
}`)
	assertContains(t, out, `call ptr @malloc`)
	assertContains(t, out, `load i64, ptr`)
	assertContains(t, out, `ret i64`)
}

func TestEmitRingPopFront(t *testing.T) {
	out := compileLL(t, `
fn pop_first(r: ring<i64>) -> option<i64> {
	return ring_pop_front(r)
}`)
	assertContains(t, out, `ring.pop.empty`)
	assertContains(t, out, `ring.pop.do`)
	assertContains(t, out, `ring.pop.done`)
	assertContains(t, out, `icmp eq i64`)
	assertContains(t, out, `call ptr @malloc`)
	assertContains(t, out, `phi ptr`)
}

func TestEmitMapNewErrors(t *testing.T) {
	_, err := compileLLErr(t, `
fn f() -> unit {
	let m: map<i64, i64> = map_new()
	return unit
}`)
	if err == nil {
		t.Fatal("expected compile error for map_new in LLVM backend, got none")
	}
	if !strings.Contains(err.Error(), "map_new") {
		t.Errorf("expected error to mention 'map_new', got: %v", err)
	}
}

func TestEmitBoxDrop(t *testing.T) {
	out := compileLL(t, `
fn f() -> unit {
	let b: box<i64> = box_new(1)
	box_drop(b)
	return unit
}`)
	assertContains(t, out, `call ptr @malloc`)
	assertContains(t, out, `call void @free`)
}

// ── pure → memory(none) transparency ─────────────────────────────────────────

// TestPureFnGetsMemoryNoneAttr verifies that a pure function's LLVM IR carries
// the memory(none) nounwind attributes. This is a machine-verifiable proof of
// purity: LLVM's own verifier rejects any memory(none) function that loads or
// stores, so the purity annotation is not documentation — it is a compile-time
// invariant encoded in the IR.
func TestPureFnGetsMemoryNoneAttr(t *testing.T) {
	out := compileLL(t, `fn add(a: i64, b: i64) -> i64 pure { return a + b }`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `memory(none)`)
	assertContains(t, out, `nounwind`)
}

// TestEffectfulFnNoMemoryNoneAttr verifies that effectful functions do NOT get
// memory(none) — the attribute is reserved for proven-pure functions only.
func TestEffectfulFnNoMemoryNoneAttr(t *testing.T) {
	out := compileLL(t, `fn log(s: str) -> unit effects(io) { print(s) return unit }`)
	t.Logf("LLVM IR:\n%s", out)
	if strings.Contains(out, `memory(none)`) {
		t.Error("effectful function must not get memory(none) attribute")
	}
}

// TestUnannotatedFnNoMemoryNoneAttr verifies that unannotated functions (neither
// pure nor effects-declared) also do not get memory(none).
func TestUnannotatedFnNoMemoryNoneAttr(t *testing.T) {
	out := compileLL(t, `fn double(x: i64) -> i64 { return x * 2 }`)
	t.Logf("LLVM IR:\n%s", out)
	if strings.Contains(out, `memory(none)`) {
		t.Error("unannotated function must not get memory(none) attribute")
	}
}

// ── LLVM-2: result<T,E> named struct tests ────────────────────────────────────

// TestResultTypeNamedStruct verifies that result<str,str> emits a named struct
// declaration in the IR header, not an opaque ptr.
func TestResultTypeNamedStruct(t *testing.T) {
	out := compileLL(t, `
fn maybe(flag: bool) -> result<str, str> {
    if flag { return ok("yes") }
    return err("no")
}`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `%_cnd_result_str_str = type`)
	assertContains(t, out, `i1`)
}

// TestResultOkConstructor verifies that ok(v) emits insertvalue sequences.
func TestResultOkConstructor(t *testing.T) {
	out := compileLL(t, `
fn wrap(s: str) -> result<str, str> {
    return ok(s)
}`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `insertvalue %_cnd_result_str_str zeroinitializer, i1 1, 0`)
	assertContains(t, out, `insertvalue %_cnd_result_str_str`)
}

// TestResultErrConstructor verifies that err(e) emits insertvalue with discriminant 0.
func TestResultErrConstructor(t *testing.T) {
	out := compileLL(t, `
fn fail(s: str) -> result<str, str> {
    return err(s)
}`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `insertvalue %_cnd_result_str_str zeroinitializer, i1 0, 0`)
}

// TestResultMatchExtractvalue verifies that match on result<T,E> uses extractvalue
// to read the discriminant and branch, not a ptr dereference.
func TestResultMatchExtractvalue(t *testing.T) {
	out := compileLL(t, `
fn unwrap(r: result<str, str>) -> str {
    return match r {
        ok(v) => v
        err(e) => "fallback"
    }
}`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `extractvalue %_cnd_result_str_str`)
	assertContains(t, out, `result.ok`)
	assertContains(t, out, `result.err`)
}

// TestResultMustExtractvalue verifies that must{} on result<T,E> uses extractvalue.
func TestResultMustExtractvalue(t *testing.T) {
	out := compileLL(t, `
fn run(r: result<i64, str>) -> i64 {
    let v = r must { ok(n) => n   err(_) => 0 }
    return v
}`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `extractvalue %_cnd_result_i64_str`)
	assertContains(t, out, `must.ok`)
	assertContains(t, out, `must.err`)
}

// TestResultI64TypeDecl verifies that result<i64,str> is declared as a named struct.
func TestResultI64TypeDecl(t *testing.T) {
	out := compileLL(t, `
fn divide(a: i64, b: i64) -> result<i64, str> {
    if b == 0 { return err("div by zero") }
    return ok(a / b)
}`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `%_cnd_result_i64_str = type { i1, i64, ptr }`)
}

// ── LLVM-3: ? as extractvalue+br+ret ─────────────────────────────────────────

// TestPropagateExprExtractvalue verifies that expr? emits extractvalue on the
// discriminant, branches to ok/err paths, and returns early on the err path.
func TestPropagateExprExtractvalue(t *testing.T) {
	out := compileLL(t, `
fn parse(s: str) -> result<i64, str> {
    return err(s)
}
fn run(s: str) -> result<i64, str> {
    let v = parse(s)?
    return ok(v)
}`)
	t.Logf("LLVM IR:\n%s", out)
	assertContains(t, out, `extractvalue %_cnd_result_i64_str`)
	assertContains(t, out, `prop.ok`)
	assertContains(t, out, `prop.err`)
}

// TestPropagateExprEarlyReturn verifies that the err path of ? emits a ret
// instruction with the wrapped error, not a branch to merge.
func TestPropagateExprEarlyReturn(t *testing.T) {
	out := compileLL(t, `
fn inner(s: str) -> result<i64, str> { return err(s) }
fn outer(s: str) -> result<i64, str> {
    let v = inner(s)?
    return ok(v + 1)
}`)
	t.Logf("LLVM IR:\n%s", out)
	// prop.err block must contain a ret instruction
	assertContains(t, out, `prop.err`)
	assertContains(t, out, `ret %_cnd_result_i64_str`)
}

// TestPropagateExprChained verifies that multiple ? in one function each
// get their own prop.ok/prop.err labels.
func TestPropagateExprChained(t *testing.T) {
	out := compileLL(t, `
fn step(s: str) -> result<str, str> { return ok(s) }
fn pipeline(s: str) -> result<str, str> {
    let a = step(s)?
    let b = step(a)?
    return ok(b)
}`)
	t.Logf("LLVM IR:\n%s", out)
	// Two ? operators → two pairs of prop.ok/prop.err labels
	if strings.Count(out, "prop.ok") < 2 {
		t.Errorf("expected at least 2 prop.ok labels, got:\n%s", out)
	}
	if strings.Count(out, "prop.err") < 2 {
		t.Errorf("expected at least 2 prop.err labels, got:\n%s", out)
	}
}
